language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -U pip
  - pip install -r requirements.txt

script:
  - flake8 src/
  - coverage run src/manage.py test src/
  - coverage report
