language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -U pip pipenv
  - pipenv install

script:
  - pipenv run flake8 src/
  - pipenv run coverage run src/manage.py test
